### PR TITLE
Update (SUPdate?) README.md

### PR DESCRIPTION
**Pull request by gregcaporaso**
@lizgehret, what do you think?

### CODE REVIEW

**Comment by gregcaporaso** [comment]
If you're good with this, I'll toss a definition in the DWQ2 glossary and link to it from here.

**Comment by lizgehret** [comment]
lgtm @gregcaporaso! lol SUPdate, i love it.

**Comment by gregcaporaso** [comment]
Ok, I linked to the definition - this is ready to go @lizgehret. Thanks!

**Comment by lizgehret** [comment]
lgtm! 🏄🏼‍♀️🌊

**Pull request merged**
